### ISSUE TITLE
Review of the basicdoc models

### ISSUE THREAD

**Issue by VasBu** [metanorma/basicdoc-models#3]
Аll models need to be revised and updated according the diagrams posted to the home page of this repo.

**Comment by VasBu** [comment]
All 9 models (diagrams) has been revised and updated respectively on 22/08/2018, including style/configuration for the diagrams provided by @ronaldtse .
Type of updates are documented in every source file.

- [PNG.zip](https://github.com/riboseinc/basicdoc-models/files/2309507/PNG.zip)
- [SVG.zip](https://github.com/riboseinc/basicdoc-models/files/2309511/SVG.zip)
- [Source FIles.zip](https://github.com/riboseinc/basicdoc-models/files/2309510/Source.FIles.zip)

**Comment by opoudjis** [comment]
@ronaldtse is there a task for me here?

**Comment by ronaldtse** [comment]
@opoudjis Yes! We should describe the BasicDoc structure using a RSD document here, and integrate the model images into the RSD document using the provided PlantUML files ("Source Files")

**Comment by opoudjis** [comment]
... A new ticket, presumably. There's already a Metanorma spec in development; would the writeup be restricted to the security and changes? In any case, that constitutes a new ticket.

**Comment by ronaldtse** [comment]
The Metanorma model will have to be a separate document.

**Comment by ronaldtse** [comment]
Integration of PlantUML toolchain done in efd046e6411b17891340f856a7ac9d1dd823e6eb. Thanks @VasBu !
