### ISSUE TITLE
Relax paragraph ID presence

### ISSUE THREAD

**Issue by andrew2net** [metanorma/basicdoc-models#32]
We need `p[@id]` in `paragraph-with-footnote` to be optional. The `paragraph-with-footnote` used in the abstract and we convert RFC's `<t>` to `<p>` without ID.

**Comment by opoudjis** [comment]
I could not refactor RNG easily to do this, and basicdoc.rnc has gone from looking beautiful to looking like vomit. I am not grateful to you, Andrej.

**Comment by opoudjis** [comment]
it does at least give me the chance to do some tidyup downstream...
