### ISSUE TITLE
Document BasicDoc

### ISSUE THREAD

**Issue by opoudjis** [metanorma/basicdoc-models#4]
> We should describe the BasicDoc structure using a RSD document here, and integrate the model images into the RSD document using the provided PlantUML files ("Source Files")

**Comment by opoudjis** [comment]
@ronaldtse Is this not a subset of the ISO documentation of Metanorma? If not, how is it different?

**Comment by ronaldtse** [comment]
Yes, it is a subset. However it is probably beneficial to split it out.

**Comment by opoudjis** [comment]
Ok, I will just use the same text for now, and restrict scope to Basic Model.
