### ISSUE TITLE
version/version => version/draft

### ISSUE THREAD

**Issue by opoudjis** [metanorma/basicdoc-models#5]
At some time in the past few months, we had agreed to rename version/version to version/draft. Please confirm that's still the case; I will need to change the published diagrams here.

**Comment by ronaldtse** [comment]
@opoudjis could you help remind me what this ticket is about? 😓

**Comment by opoudjis** [comment]
The UML diagram has version/version, but we changed this in the XML to version/draft. I'm confirming that we changed that, and need to change the UML to match.

**Comment by ronaldtse** [comment]
Sure let's go ahead. Thanks!
